# Generated by Django 3.1.7 on 2021-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_auto_20210412_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='wrkexp',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
