# Generated by Django 3.1.7 on 2021-04-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210411_1207'),
        ('jobs_app', '0004_jobdetails_jobreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(max_length=10, null=True)),
                ('rejected', models.CharField(max_length=10, null=True)),
                ('cand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.canreg')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_app.jobdetails')),
            ],
        ),
    ]
