# Generated by Django 3.1.7 on 2021-04-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0005_jobsapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsapplied',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
