# Generated by Django 3.1.7 on 2021-04-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210411_1207'),
        ('jobs_app', '0007_jobsapplied_com'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500, null=True)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.CharField(default='not viewed', max_length=250, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.canreg')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.compreg')),
            ],
        ),
    ]
