# Generated by Django 3.1.7 on 2021-04-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210411_1207'),
        ('jobs_app', '0010_feedback_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(null=True, upload_to='', verbose_name='files/')),
                ('message', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.canreg')),
                ('jobs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs_app.jobsapplied')),
            ],
        ),
    ]
