# Generated by Django 3.1.7 on 2021-04-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compreg',
            name='rnum',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
