# Generated by Django 3.1.7 on 2021-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_compreg_comtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compreg',
            name='Desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='compreg',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compreg',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
