# Generated by Django 3.1.7 on 2021-04-04 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20210404_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('place', models.CharField(max_length=30, null=True)),
                ('desc', models.CharField(max_length=250, null=True)),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('resume', models.FileField(null=True, upload_to='', verbose_name='resumes/')),
                ('qual', models.CharField(max_length=50, null=True)),
                ('workexp', models.CharField(max_length=300, null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('others', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
